chore: add test to check WWW-Authenticate header

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -75,10 +75,18 @@ jobs:
 
           # Test protected route without header
           echo "Testing protected route without header..."
-          response=$(curl -s -w "\n%{http_code}" --max-time 30 -L http://0.0.0.0:8000/protected)
+          response=$(curl -s -i -w "\n%{http_code}" --max-time 30 -L http://0.0.0.0:8000/protected)
           status_code=$(echo "$response" | tail -n1)
           if [ "$status_code" -ne 402 ]; then
             echo "Error: Protected route without header returned status $status_code, expected 402"
+            docker logs nginx-lnurl
+            exit 1
+          fi
+          
+          # Check if WWW-Authenticate header is present
+          if ! echo "$response" | grep -q 'WWW-Authenticate: L402 macaroon='; then
+            echo "Error: WWW-Authenticate header is missing in the 402 response"
+            echo "$response"
             docker logs nginx-lnurl
             exit 1
           fi
@@ -141,10 +149,18 @@ jobs:
 
           # Test protected route without header
           echo "Testing protected route without header..."
-          response=$(curl -s -w "\n%{http_code}" --max-time 30 -L http://0.0.0.0:8000/protected)
+          response=$(curl -s -i -w "\n%{http_code}" --max-time 30 -L http://0.0.0.0:8000/protected)
           status_code=$(echo "$response" | tail -n1)
           if [ "$status_code" -ne 402 ]; then
             echo "Error: Protected route without header returned status $status_code, expected 402"
+            docker logs nginx-nwc
+            exit 1
+          fi
+          
+          # Check if WWW-Authenticate header is present
+          if ! echo "$response" | grep -q 'WWW-Authenticate: L402 macaroon='; then
+            echo "Error: WWW-Authenticate header is missing in the 402 response"
+            echo "$response"
             docker logs nginx-nwc
             exit 1
           fi
@@ -226,10 +242,18 @@ jobs:
 
           # Test protected route without header
           echo "Testing protected route without header..."
-          response=$(curl -s -w "\n%{http_code}" --max-time 30 -L http://0.0.0.0:8000/protected)
+          response=$(curl -s -i -w "\n%{http_code}" --max-time 30 -L http://0.0.0.0:8000/protected)
           status_code=$(echo "$response" | tail -n1)
           if [ "$status_code" -ne 402 ]; then
             echo "Error: Protected route without header returned status $status_code, expected 402"
+            docker logs nginx-lnd
+            exit 1
+          fi
+          
+          # Check if WWW-Authenticate header is present
+          if ! echo "$response" | grep -q 'WWW-Authenticate: L402 macaroon='; then
+            echo "Error: WWW-Authenticate header is missing in the 402 response"
+            echo "$response"
             docker logs nginx-lnd
             exit 1
           fi
